#!/bin/bash

#================================================
#      Prevent overwriting important files
#================================================
case $1 in
	QPU|GPU|blochSphere|measurementGraph|huts)
		echo "Error: filename can't be" $1"."
		exit 1
		;;
esac
 
#===============================================
#            	Making new file
#===============================================
touch $1.py

#The new file will contain one of two example scripts.
R=$(($RANDOM % 2))

if [ $R = 0 ]; then
cat >$1.py <<'EOM'
#This script is an example.
#Feel free to add to and delete from this script as you like,
#in order to create your own script.

# Importing libararies,
# namely the Quantum Processing Unit (QPU),
# and the Graphical Processing Unit (GPU).
from QPU import *
import GPU.blochSphere
import GPU.measurementGraph

#This is script does 100 shots of a series of quantum gates with two qbit.
#At the end of each shot, one of the qbits is measured.
#The measured value is saved for later use.

# First, a container is created to save all the measured values.
measurements = []

# Now, the series of quantum gates will be executed 100 times.
for shot in range(100):
	
	# Two qbits are created.
	q0 = qbit()
	q1 = qbit()
	
	# Some gates are applied.
	gate(Pauli_X, q1)
	gate(Hadamard, q0)
	gate(Hadamard, q1)
	
	gate(CNOT, q0, q1)
	
	gate(Hadamard, q0)

	# After all of the gates have been applied, qbit q0 is measured.
	# Since this script is repeated 100 times,
	#  and we don't want every single measurement to be printed,
	# `Print` is set to `False`.
	measurements.append(measure(q0, Print=False))


# Finally, the measured values are graphed.
GPU.measurementGraph.showGraph(measurements) 

# See documentation.md for more functionallities!

EOM

elif [ $R = 1 ]; then
cat >$1.py <<'EOM'
# This script is an example.
# Feel free to add to and delete from this script as you like,
# in order to create your own script.

# Importing libararies,
# namely the Quantum Processing Unit (QPU),
# and the Graphical Processing Unit (GPU).
from QPU import *
import GPU.blochSphere
import GPU.measurementGraph

# This script creates two qbits,
# applies a couple of gates to them,
# and finally displays both qbits on the bloch sphere.

# Creating the two qbits.
q0 = qbit()
q1 = qbit()

# Applying the gates.
gate(Rx(45, angleUnit='degree'), q0) # Here, we want to rotate q0 45°.
				     # Therefore, `angleUnit` is set to 'degree'.
				     # The standard angleUnit is radians.
gate(T_dagger, q1)

gate(CNOT, q0, q1)

gate(Hadamard, q0)

# Finally, the two qbits are displayed on the bloch sphere.
GPU.blochSphere.drawBlochSphere([q0, q1])

# See documentation.md for more functionallity!


EOM

else
echo "Error: $R is neither 0 nor 1"

fi
